package com.iumrah.beta.ui.transferservice

import androidx.compose.animation.AnimatedVisibility
import androidx.compose.foundation.Image
import androidx.compose.foundation.background
import androidx.compose.foundation.border
import androidx.compose.foundation.horizontalScroll
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.shape.CircleShape
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.foundation.verticalScroll
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.Text
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.clip
import androidx.compose.ui.graphics.Brush
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.layout.ContentScale
import androidx.compose.ui.res.painterResource
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import com.iumrah.beta.R
import com.iumrah.beta.core.navigation.AppChromeStore
import com.iumrah.beta.core.settings.AppLanguage
import com.iumrah.beta.ui.components.IumrahPressable
import com.iumrah.beta.ui.cupertino.CupertinoIcon
import com.iumrah.beta.ui.cupertino.CupertinoSymbol
import com.iumrah.beta.ui.homeflow.InternalNavBar
import com.iumrah.beta.ui.homeflow.tr

enum class VehicleKind(val model:String,val people:Int,val bags:Int,val image:Int){
    MALIBU("Chevrolet Malibu",3,2,R.drawable.transfer_malibu),
    CARNIVAL("Kia Carnival",7,5,R.drawable.transfer_carnival),
    YUKON("GMC Yukon",6,5,R.drawable.transfer_yukon)
}

@Composable fun IumrahTransferServiceScreen(language:AppLanguage,chrome:AppChromeStore){var selected by remember{mutableStateOf(VehicleKind.MALIBU)};var notice by remember{mutableStateOf(false)};var train by remember{mutableStateOf(false)};Column(Modifier.fillMaxSize().background(MaterialTheme.colorScheme.background)){InternalNavBar("iumrah Transfer",chrome);Column(Modifier.fillMaxSize().verticalScroll(rememberScrollState()).padding(horizontal=18.dp,vertical=14.dp),verticalArrangement=Arrangement.spacedBy(22.dp)){Column(verticalArrangement=Arrangement.spacedBy(7.dp)){Text(tr(language,"Выберите трансфер","Choose your transfer","Transferni tanlang","Трансферни танланг"),fontSize=32.sp,fontWeight=FontWeight.Bold,letterSpacing=(-.7).sp);Text(tr(language,"Тот же выбор автомобиля и Haramain, который используется внутри iumrah Configurator.","The same vehicle and Haramain choices used inside iumrah Configurator.","iumrah Configurator ichidagi xuddi shu avtomobil va Haramain tanlovi.","iumrah Configurator ичидаги худди шу автомобиль ва Haramain танлови."),fontSize=14.sp,color=MaterialTheme.colorScheme.onSurface.copy(alpha=.55f))};VehiclePicker(language,selected){selected=it};VehicleInfo(language,selected);HaramainCard(language,train){train=!train};AnimatedVisibility(notice){PackageOnlyNotice(language)};IumrahPressable({notice=true},Modifier.fillMaxWidth().height(56.dp),cornerRadius=19.dp,background=Color.Black){Row(Modifier.fillMaxSize().padding(horizontal=17.dp),verticalAlignment=Alignment.CenterVertically){CupertinoIcon(CupertinoSymbol.Car,null,Modifier.size(19.dp),tint=Color.White);Spacer(Modifier.width(10.dp));Text(tr(language,"Заказать автомобиль","Book vehicle","Avtomobil buyurtma qilish","Автомобиль буюртма қилиш"),color=Color.White,fontWeight=FontWeight.Bold,fontSize=16.sp);Spacer(Modifier.weight(1f));CupertinoIcon(CupertinoSymbol.ArrowRight,null,Modifier.size(16.dp),tint=Color.White)}};Spacer(Modifier.height(24.dp))}}}

@Composable private fun VehiclePicker(language:AppLanguage,selected:VehicleKind,onSelect:(VehicleKind)->Unit){Column(horizontalAlignment=Alignment.CenterHorizontally,verticalArrangement=Arrangement.spacedBy(12.dp)){VehicleStage(language,selected);Row(horizontalArrangement=Arrangement.spacedBy(7.dp)){VehicleKind.entries.forEach{v->Box(Modifier.width(if(v==selected)24.dp else 7.dp).height(7.dp).background(if(v==selected)MaterialTheme.colorScheme.onSurface else MaterialTheme.colorScheme.onSurface.copy(alpha=.22f),CircleShape))}};Row(horizontalArrangement=Arrangement.spacedBy(8.dp)){VehicleKind.entries.forEach{v->IumrahPressable({onSelect(v)},Modifier.weight(1f).height(38.dp),cornerRadius=13.dp,background=if(v==selected)Color.Black else MaterialTheme.colorScheme.surfaceVariant){Box(Modifier.fillMaxSize(),contentAlignment=Alignment.Center){Text(v.model.substringAfterLast(' '),fontSize=11.sp,fontWeight=FontWeight.Bold,color=if(v==selected)Color.White else MaterialTheme.colorScheme.onSurface)}}}}}}
@Composable private fun VehicleStage(language:AppLanguage,v:VehicleKind){Box(Modifier.fillMaxWidth().height(330.dp).background(Color.White,RoundedCornerShape(36.dp)).border(.8.dp,Color.Black.copy(alpha=.055f),RoundedCornerShape(36.dp))){Column(Modifier.fillMaxSize()){Row(Modifier.padding(horizontal=22.dp).padding(top=18.dp),verticalAlignment=Alignment.Top){Text(vehicleClass(language,v),fontSize=12.sp,fontWeight=FontWeight.Bold,letterSpacing=1.1.sp,color=Color.Gray);Spacer(Modifier.weight(1f));Text("0${VehicleKind.entries.indexOf(v)+1}",fontSize=42.sp,fontWeight=FontWeight.Black,color=Color.Black.copy(alpha=.06f))};Spacer(Modifier.weight(1f));Image(painterResource(v.image),null,Modifier.fillMaxWidth().height(180.dp).padding(horizontal=if(v==VehicleKind.MALIBU)8.dp else 0.dp),contentScale=ContentScale.Fit);Spacer(Modifier.weight(1f));Row(Modifier.padding(horizontal=22.dp).padding(bottom=20.dp),verticalAlignment=Alignment.CenterVertically){Text(v.model,fontSize=24.sp,fontWeight=FontWeight.Bold,color=Color.Black);Spacer(Modifier.weight(1f));CupertinoIcon(CupertinoSymbol.Persons,null,Modifier.size(15.dp),tint=Color.Gray);Spacer(Modifier.width(5.dp));Text(v.people.toString(),fontSize=12.sp,fontWeight=FontWeight.Bold,color=Color.Gray)}}}}
@Composable private fun VehicleInfo(language:AppLanguage,v:VehicleKind){Column(Modifier.fillMaxWidth().background(MaterialTheme.colorScheme.surface,RoundedCornerShape(28.dp)).border(.7.dp,MaterialTheme.colorScheme.onSurface.copy(alpha=.06f),RoundedCornerShape(28.dp)).padding(18.dp),verticalArrangement=Arrangement.spacedBy(16.dp)){Row(verticalAlignment=Alignment.Top){Column(Modifier.weight(1f)){Text(vehicleClass(language,v),fontSize=12.sp,fontWeight=FontWeight.Bold,letterSpacing=.8.sp,color=MaterialTheme.colorScheme.onSurface.copy(alpha=.5f));Text(v.model,fontSize=27.sp,fontWeight=FontWeight.Bold)};Row(verticalAlignment=Alignment.CenterVertically){CupertinoIcon(CupertinoSymbol.CheckCircleFill,null,Modifier.size(15.dp),tint=Color(0xFF34C759));Spacer(Modifier.width(4.dp));Text(tr(language,"Доступен","Available","Mavjud","Мавжуд"),fontSize=12.sp,fontWeight=FontWeight.Bold,color=Color(0xFF34C759))}};Text(vehicleDescription(language,v),fontSize=14.sp,color=MaterialTheme.colorScheme.onSurface.copy(alpha=.55f));Row(horizontalArrangement=Arrangement.spacedBy(8.dp)){Metric(CupertinoSymbol.Persons,tr(language,"до ${v.people} гостей","up to ${v.people} guests","${v.people} gacha mehmon","${v.people} гача меҳмон"));Metric(CupertinoSymbol.SuitcaseFill,tr(language,"багаж ${v.bags}","${v.bags} bags","${v.bags} bagaj","${v.bags} багаж"))}}}
@Composable private fun HaramainCard(language:AppLanguage,selected:Boolean,toggle:()->Unit){Column(Modifier.fillMaxWidth().background(MaterialTheme.colorScheme.surface,RoundedCornerShape(30.dp)).border(.8.dp,if(selected)Color(0xFF34C759).copy(alpha=.28f) else MaterialTheme.colorScheme.onSurface.copy(alpha=.06f),RoundedCornerShape(30.dp)).padding(18.dp),verticalArrangement=Arrangement.spacedBy(16.dp)){Row(verticalAlignment=Alignment.CenterVertically){Image(painterResource(R.drawable.haramain_mark),null,Modifier.size(48.dp).clip(RoundedCornerShape(14.dp)),contentScale=ContentScale.Fit);Spacer(Modifier.width(12.dp));Column(Modifier.weight(1f)){Text("Haramain High Speed Railway",fontSize=16.sp,fontWeight=FontWeight.Bold);Text(tr(language,"Мекка ↔ Медина","Makkah ↔ Madinah","Makka ↔ Madina","Макка ↔ Мадина"),fontSize=12.sp,color=MaterialTheme.colorScheme.onSurface.copy(alpha=.5f))};if(selected)CupertinoIcon(CupertinoSymbol.CheckCircleFill,null,Modifier.size(21.dp),tint=Color(0xFF34C759))};Row(Modifier.horizontalScroll(rememberScrollState()),horizontalArrangement=Arrangement.spacedBy(10.dp)){listOf(R.drawable.haramain_hero,R.drawable.haramain_gallery_station,R.drawable.haramain_gallery_interior,R.drawable.haramain_gallery_train).forEach{res->Image(painterResource(res),null,Modifier.size(238.dp,145.dp).clip(RoundedCornerShape(20.dp)),contentScale=ContentScale.Crop)}};Text(tr(language,"Можно заменить междугородний участок Мекка ↔ Медина поездом Haramain. Автомобиль до станции и после прибытия остаётся частью трансфера.","You can replace the Makkah ↔ Madinah intercity leg with Haramain. The vehicle to the station and after arrival remains part of the transfer.","Makka ↔ Madina shaharlararo qismini Haramain poyezdiga almashtirish mumkin.","Макка ↔ Мадина шаҳарлараро қисмини Haramain поездига алмаштириш мумкин."),fontSize=14.sp,color=MaterialTheme.colorScheme.onSurface.copy(alpha=.55f));Row(horizontalArrangement=Arrangement.spacedBy(8.dp)){Metric(CupertinoSymbol.SignalWave,"300 km/h");Metric(CupertinoSymbol.CalendarClock,"≈ 2h 20m");Metric(CupertinoSymbol.SignalWave,"Wi‑Fi")};IumrahPressable(toggle,Modifier.fillMaxWidth().height(58.dp),cornerRadius=20.dp,background=if(selected)Color(0xFF34C759) else Color.Black){Row(Modifier.fillMaxSize().padding(horizontal=17.dp),verticalAlignment=Alignment.CenterVertically){CupertinoIcon(if(selected)CupertinoSymbol.CheckCircleFill else CupertinoSymbol.Plus,null,Modifier.size(18.dp),tint=Color.White);Spacer(Modifier.width(8.dp));Text(if(selected)tr(language,"Поезд выбран","Train selected","Poyezd tanlandi","Поезд танланди") else tr(language,"Выбрать Haramain","Choose Haramain","Haramainni tanlash","Haramainни танлаш"),fontWeight=FontWeight.Bold,color=Color.White);Spacer(Modifier.weight(1f));CupertinoIcon(if(selected)CupertinoSymbol.Checkmark else CupertinoSymbol.ArrowRight,null,Modifier.size(15.dp),tint=Color.White)}}}}
@Composable private fun Metric(icon:CupertinoSymbol,text:String){Row(Modifier.height(36.dp).background(MaterialTheme.colorScheme.surfaceVariant,CircleShape).padding(horizontal=10.dp),verticalAlignment=Alignment.CenterVertically){CupertinoIcon(icon,null,Modifier.size(14.dp));Spacer(Modifier.width(5.dp));Text(text,fontSize=11.sp,fontWeight=FontWeight.SemiBold)}}
@Composable private fun PackageOnlyNotice(language:AppLanguage){Row(Modifier.fillMaxWidth().background(Brush.linearGradient(listOf(Color(0xFFFF9500).copy(alpha=.18f),Color(0xFFFF9500).copy(alpha=.07f))),RoundedCornerShape(26.dp)).border(.8.dp,Color(0xFFFF9500).copy(alpha=.22f),RoundedCornerShape(26.dp)).padding(18.dp),verticalAlignment=Alignment.Top){CupertinoIcon(CupertinoSymbol.ExclamationCircle,null,Modifier.size(22.dp),tint=Color(0xFFEB6B14));Spacer(Modifier.width(13.dp));Column{Text(tr(language,"Пока только внутри Umrah-пакета","Currently available only inside an Umrah package","Hozircha faqat Umrah paketi ichida","Ҳозирча фақат Umrah пакети ичида"),fontWeight=FontWeight.Bold);Spacer(Modifier.height(5.dp));Text(tr(language,"Отдельное бронирование трансфера ещё не открыто. Соберите Umrah-пакет — выбранный автомобиль и Haramain будут доступны внутри конфигуратора.","Standalone transfer booking is not open yet. Build an Umrah package and choose the vehicle or Haramain inside the configurator.","Alohida transfer bronlash hali ochilmagan.","Алоҳида transfer бронлаш ҳали очилмаган."),fontSize=13.sp,color=MaterialTheme.colorScheme.onSurface.copy(alpha=.55f))}}}
private fun vehicleClass(l:AppLanguage,v:VehicleKind)=when(v){VehicleKind.CARNIVAL->tr(l,"СЕМЕЙНЫЙ","FAMILY","OILAVIY","ОИЛАВИЙ");VehicleKind.YUKON->"VIP";VehicleKind.MALIBU->tr(l,"КОМПАКТНЫЙ","COMPACT","IXCHAM","ИХЧАМ")}
private fun vehicleDescription(l:AppLanguage,v:VehicleKind)=when(v){VehicleKind.CARNIVAL->tr(l,"Комфортный минивэн для семьи и небольшой группы.","A comfortable minivan for families and small groups.","Oila va kichik guruh uchun qulay miniven.","Оила ва кичик гуруҳ учун қулай минивен.");VehicleKind.YUKON->tr(l,"Просторный VIP SUV для более приватной поездки.","A spacious VIP SUV for a more private journey.","Xususiyroq safar uchun keng VIP SUV.","Хусусийроқ сафар учун кенг VIP SUV.");VehicleKind.MALIBU->tr(l,"Городской седан для компактного маршрута.","A city sedan for a compact itinerary.","Ixcham yo‘nalish uchun shahar sedani.","Ихчам йўналиш учун шаҳар седани.")}
