package com.iumrah.beta.ui.story

import androidx.compose.foundation.Image
import androidx.compose.foundation.background
import androidx.compose.foundation.border
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.foundation.verticalScroll
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.clip
import androidx.compose.ui.graphics.Brush
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.layout.ContentScale
import androidx.compose.ui.res.painterResource
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import com.iumrah.beta.R
import com.iumrah.beta.core.navigation.AppChromeStore
import com.iumrah.beta.core.settings.AppLanguage
import com.iumrah.beta.ui.cupertino.CupertinoIcon
import com.iumrah.beta.ui.cupertino.CupertinoSymbol
import com.iumrah.beta.ui.homeflow.InternalNavBar
import com.iumrah.beta.ui.homeflow.tr

@Composable fun IumrahStoryScreen(language:AppLanguage,chrome:AppChromeStore){Column(Modifier.fillMaxSize().background(MaterialTheme.colorScheme.background)){InternalNavBar(tr(language,"О проекте iumrah","About iumrah","iumrah haqida","iumrah ҳақида"),chrome);Column(Modifier.fillMaxSize().verticalScroll(rememberScrollState()).padding(horizontal=18.dp,vertical=12.dp),verticalArrangement=Arrangement.spacedBy(26.dp)){StoryHero(language);Intro(language);ExperienceStrip(language);StoryImage(R.drawable.about_iumrah_pilgrims,310);TextCard(tr(language,"ПОЧЕМУ IUMRAH","WHY IUMRAH","NEGA IUMRAH","НЕГА IUMRAH"),tr(language,"Самостоятельность без потери поддержки","Freedom without losing support","Yordamni yo‘qotmasdan mustaqillik","Ёрдамни йўқотмасдан мустақиллик"),tr(language,"Вы выбираете даты, людей, уровень отеля и темп поездки. iumrah связывает операционные части и остаётся рядом, когда нужна помощь.","You choose dates, people, hotel level and the pace of the journey. iumrah connects the operational pieces and stays with you when you need help.","Sanalar, hamrohlar, mehmonxona darajasi va safar tempini siz tanlaysiz. iumrah qolgan qismlarni bog‘laydi.","Саналар, ҳамроҳлар, меҳмонхона даражаси ва сафар темпини сиз танлайсиз. iumrah қолган қисмларни боғлайди."));StoryImage(R.drawable.about_iumrah_kaaba_touch,390);Principles(language);StoryImage(R.drawable.about_iumrah_map_dark,225);TextCard(tr(language,"КУДА МЫ ИДЁМ","THE DIRECTION","YO‘NALISH","ЙЎНАЛИШ"),tr(language,"Nusuk — для разрешений. iumrah — для всей остальной поездки.","Nusuk for permits. iumrah for the rest of the journey.","Nusuk — ruxsatlar uchun. iumrah — safarning qolgan qismi uchun.","Nusuk — рухсатлар учун. iumrah — сафарнинг қолган қисми учун."),tr(language,"Цель — спокойный цифровой спутник до, во время и после Umrah: планирование, бронирование, статус, сопровождение и живая Care-поддержка в одной системе.","The goal is a calm digital companion before, during and after Umrah: planning, booking, status, guidance and human Care in one system.","Maqsad — Umradan oldin, davomida va keyin rejalashtirish, bron, holat va Care’ni bir tizimda birlashtirish.","Мақсад — Умрадан олдин, давомида ва кейин режалаштириш, брон, ҳолат ва Care’ни бир тизимда бирлаштириш."));StoryImage(R.drawable.about_iumrah_kaaba_corner,360);Closing(language);Spacer(Modifier.height(20.dp))}}}
@Composable private fun StoryHero(l:AppLanguage){Box(Modifier.fillMaxWidth().height(390.dp).clip(RoundedCornerShape(32.dp)).border(.8.dp,MaterialTheme.colorScheme.onSurface.copy(alpha=.06f),RoundedCornerShape(32.dp))){Image(painterResource(R.drawable.about_iumrah_map_light),null,Modifier.fillMaxSize(),contentScale=ContentScale.Crop);Box(Modifier.fillMaxSize().background(Brush.verticalGradient(listOf(Color.Transparent,Color.Transparent,Color.Black.copy(alpha=.68f)))));Column(Modifier.align(Alignment.BottomStart).padding(20.dp),verticalArrangement=Arrangement.spacedBy(10.dp)){Text(tr(l,"3 ГОДА ОПЫТА","3 YEARS OF EXPERIENCE","3 YILLIK TAJRIBA","3 ЙИЛЛИК ТАЖРИБА"),fontSize=12.sp,fontWeight=FontWeight.Bold,letterSpacing=1.2.sp,color=Color.White.copy(alpha=.78f));Text(tr(l,"Персональная Umrah, построенная вокруг Вас","A personal Umrah, built around you","Sizga mos shaxsiy Umra","Сизга мос шахсий Умра"),fontSize=31.sp,fontWeight=FontWeight.Bold,letterSpacing=(-.65).sp,color=Color.White,lineHeight=34.sp);Text(tr(l,"iumrah вырос из реального опыта паломников и простой идеи: человек должен понимать и контролировать свою поездку, а не зависеть от большой безличной группы.","iumrah grew from real pilgrimage experience and a simple idea: the pilgrim should understand and control the journey, not depend on a large anonymous group.","iumrah haqiqiy ziyorat tajribasidan va oddiy g‘oyadan tug‘ilgan.","iumrah ҳақиқий зиёрат тажрибасидан ва оддий ғоядан туғилган."),fontSize=14.sp,color=Color.White.copy(alpha=.82f),lineHeight=19.sp)}}}
@Composable private fun Intro(l:AppLanguage){Column(verticalArrangement=Arrangement.spacedBy(10.dp)){Text("iumrah",fontSize=12.sp,fontWeight=FontWeight.Bold,letterSpacing=1.sp,color=MaterialTheme.colorScheme.onSurface.copy(alpha=.5f));Text(tr(l,"Одна поездка. Одна понятная система.","One journey. One clear system.","Bitta safar. Bitta tushunarli tizim.","Битта сафар. Битта тушунарли тизим."),fontSize=29.sp,fontWeight=FontWeight.Bold,letterSpacing=(-.55).sp);Text(tr(l,"Перелёт, отель, трансфер, сопровождение, Care и статус поездки соединены в одном месте, чтобы паломнику не приходилось собирать путешествие из разрозненных чатов и обещаний.","Flights, hotel, transfer, guidance, Care and trip status are connected in one place so the pilgrim does not have to assemble the journey from scattered chats and promises.","Parvoz, mehmonxona, transfer, yo‘l-yo‘riq, Care va safar holati bir joyda bog‘langan.","Парвоз, меҳмонхона, трансфер, йўл-йўриқ, Care ва сафар ҳолати бир жойда боғланган."),fontSize=16.sp,color=MaterialTheme.colorScheme.onSurface.copy(alpha=.55f),lineHeight=21.sp)}}
@Composable private fun ExperienceStrip(l:AppLanguage){Row(horizontalArrangement=Arrangement.spacedBy(10.dp)){Metric("3",tr(l,"года в этой нише","years in the niche","yil tajriba","йил тажриба"),CupertinoSymbol.CalendarClock,Modifier.weight(1f));Metric("1",tr(l,"связанная поездка","connected journey","yagona safar","ягона сафар"),CupertinoSymbol.Route,Modifier.weight(1f))}}
@Composable private fun Metric(value:String,label:String,icon:CupertinoSymbol,modifier:Modifier){Column(modifier.heightIn(min=132.dp).background(MaterialTheme.colorScheme.surface,RoundedCornerShape(24.dp)).border(.8.dp,MaterialTheme.colorScheme.onSurface.copy(alpha=.055f),RoundedCornerShape(24.dp)).padding(17.dp),verticalArrangement=Arrangement.spacedBy(9.dp)){CupertinoIcon(icon,null,Modifier.size(17.dp),tint=MaterialTheme.colorScheme.onSurface.copy(alpha=.5f));Text(value,fontSize=31.sp,fontWeight=FontWeight.Bold);Text(label,fontSize=12.sp,fontWeight=FontWeight.SemiBold,color=MaterialTheme.colorScheme.onSurface.copy(alpha=.5f))}}
@Composable private fun StoryImage(res:Int,height:Int){Image(painterResource(res),null,Modifier.fillMaxWidth().height(height.dp).clip(RoundedCornerShape(30.dp)).border(.8.dp,MaterialTheme.colorScheme.onSurface.copy(alpha=.055f),RoundedCornerShape(30.dp)),contentScale=ContentScale.Crop)}
@Composable private fun TextCard(eyebrow:String,title:String,body:String){Column(Modifier.fillMaxWidth().background(MaterialTheme.colorScheme.surface,RoundedCornerShape(28.dp)).border(.8.dp,MaterialTheme.colorScheme.onSurface.copy(alpha=.055f),RoundedCornerShape(28.dp)).padding(18.dp),verticalArrangement=Arrangement.spacedBy(10.dp)){Text(eyebrow,fontSize=12.sp,fontWeight=FontWeight.Bold,letterSpacing=1.sp,color=MaterialTheme.colorScheme.onSurface.copy(alpha=.5f));Text(title,fontSize=26.sp,fontWeight=FontWeight.Bold,letterSpacing=(-.45).sp,lineHeight=29.sp);Text(body,fontSize=14.sp,color=MaterialTheme.colorScheme.onSurface.copy(alpha=.55f),lineHeight=19.sp)}}
@Composable private fun Principles(l:AppLanguage){Column(verticalArrangement=Arrangement.spacedBy(12.dp)){Text(tr(l,"Что для нас важно","What we protect","Biz uchun muhim","Биз учун муҳим"),fontSize=26.sp,fontWeight=FontWeight.Bold);Principle(CupertinoSymbol.Eye,tr(l,"Прозрачность","Transparency","Shaffoflik","Шаффофлик"),tr(l,"Понятный статус и понятный следующий шаг.","Clear status and clear next actions.","Aniq holat va keyingi qadam.","Аниқ ҳолат ва кейинги қадам."));Principle(CupertinoSymbol.Persons,tr(l,"Персональный формат","Personal format","Shaxsiy format","Шахсий формат"),tr(l,"Поездка для Вас, семьи или друзей.","A journey for you, your family or friends.","Siz, oila yoki do‘stlar uchun safar.","Сиз, оила ёки дўстлар учун сафар."));Principle(CupertinoSymbol.HeartFill,"iumrah Care",tr(l,"Живая поддержка, когда одного приложения недостаточно.","Human support when an app alone is not enough.","Ilovaning o‘zi yetarli bo‘lmaganda inson yordami.","Илованинг ўзи етарли бўлмаганда инсон ёрдами."))}}
@Composable private fun Principle(icon:CupertinoSymbol,title:String,body:String){Row(Modifier.fillMaxWidth().background(MaterialTheme.colorScheme.surface,RoundedCornerShape(22.dp)).border(.8.dp,MaterialTheme.colorScheme.onSurface.copy(alpha=.055f),RoundedCornerShape(22.dp)).padding(16.dp),verticalAlignment=Alignment.Top){Box(Modifier.size(44.dp).background(MaterialTheme.colorScheme.surfaceVariant,RoundedCornerShape(14.dp)),contentAlignment=Alignment.Center){CupertinoIcon(icon,null,Modifier.size(18.dp))};Spacer(Modifier.width(13.dp));Column{Text(title,fontSize=16.sp,fontWeight=FontWeight.Bold);Text(body,fontSize=14.sp,color=MaterialTheme.colorScheme.onSurface.copy(alpha=.55f))}}}
@Composable private fun Closing(l:AppLanguage){TextCard("",tr(l,"Создано вокруг паломника","Built around the pilgrim","Ziyoratchi uchun yaratilgan","Зиёратчи учун яратилган"),tr(l,"Технология имеет смысл только тогда, когда делает поездку понятнее, спокойнее и персональнее. Вокруг этого стандарта мы и строим iumrah.","Technology is useful only when it makes the journey clearer, calmer and more personal. That is the standard we are building iumrah around.","Texnologiya safarni tushunarliroq, xotirjamroq va shaxsiyroq qilgandagina foydali.","Технология сафарни тушунарлироқ, хотиржамроқ ва шахсийроқ қилгандагина фойдали."))}
