package com.iumrah.beta.ui.carerequest

import android.content.Intent
import android.net.Uri
import androidx.compose.foundation.background
import androidx.compose.foundation.border
import androidx.compose.foundation.clickable
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.grid.GridCells
import androidx.compose.foundation.lazy.grid.LazyVerticalGrid
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.shape.CircleShape
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.foundation.text.BasicTextField
import androidx.compose.foundation.verticalScroll
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.text.TextStyle
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import com.iumrah.beta.core.network.APIClient
import com.iumrah.beta.core.navigation.AppChromeStore
import com.iumrah.beta.core.settings.AppLanguage
import com.iumrah.beta.core.settings.AppSettingsStore
import com.iumrah.beta.data.account.IumrahAccountStore
import com.iumrah.beta.data.care.*
import com.iumrah.beta.data.chat.ChatService
import com.iumrah.beta.data.flight.AirportSearchService
import com.iumrah.beta.models.flight.Airport
import com.iumrah.beta.ui.components.IumrahPressable
import com.iumrah.beta.ui.cupertino.*
import com.iumrah.beta.ui.homeflow.*
import com.iumrah.beta.ui.trip.ConfiguratorAirportSelector
import java.time.LocalDate
import java.time.YearMonth
import kotlinx.coroutines.launch

@Composable
fun IumrahCareRequestScreen(language:AppLanguage, airports:AirportSearchService, accountStore:IumrahAccountStore, settingsStore:AppSettingsStore, chrome:AppChromeStore){
    val accountState by accountStore.state.collectAsState(); val settings by settingsStore.state.collectAsState(); val profile=accountState.account
    var airport by remember{mutableStateOf<Airport?>(null)};var origin by remember{mutableStateOf("TAS")};var timing by remember{mutableStateOf("flexible_month")};var month by remember{mutableStateOf(YearMonth.now().plusMonths(1))};var flex by remember{mutableIntStateOf(7)};var start by remember{mutableStateOf(LocalDate.now().plusDays(21))};var end by remember{mutableStateOf(LocalDate.now().plusDays(28))}
    var adults by remember{mutableIntStateOf(2)};var children by remember{mutableIntStateOf(0)};var infants by remember{mutableIntStateOf(0)};var rooms by remember{mutableIntStateOf(1)};var scope by remember{mutableStateOf("makkah_madinah")};var firstCity by remember{mutableStateOf("jeddah")};var priority by remember{mutableStateOf("balanced")};var hotelClass by remember{mutableIntStateOf(4)};var transfer by remember{mutableStateOf("comfortable")};var direct by remember{mutableStateOf(true)};var baggage by remember{mutableStateOf(true)};var ziyarat by remember{mutableStateOf(true)};var esim by remember{mutableStateOf(true)};var guide by remember{mutableStateOf("voice")};var budget by remember{mutableStateOf("")};var notes by remember{mutableStateOf("")}
    var firstName by remember(profile,settings){mutableStateOf(profile?.firstName?.ifBlank{settings.firstName}?:settings.firstName)};var lastName by remember(profile,settings){mutableStateOf(profile?.lastName?.ifBlank{settings.lastName}?:settings.lastName)};var phone by remember(profile,settings){mutableStateOf(profile?.phone?.ifBlank{settings.whatsapp}?:settings.whatsapp)};var telegram by remember(profile,settings){mutableStateOf(profile?.telegram?.ifBlank{settings.telegram}?:settings.telegram)}
    var carePhone by remember{mutableStateOf("")};var submitting by remember{mutableStateOf(false)};var response by remember{mutableStateOf<IumrahCarePackageRequestResponse?>(null)};var error by remember{mutableStateOf<String?>(null)};val context=LocalContext.current;val scopeC=rememberCoroutineScope();val service=remember{IumrahCareRequestService()};val chatService=remember{ChatService(APIClient())}
    LaunchedEffect(Unit){carePhone=runCatching{chatService.loadCareProfile()?.phoneUZ.orEmpty()}.getOrDefault("")}
    Column(Modifier.fillMaxSize().background(MaterialTheme.colorScheme.background)){InternalNavBar(tr(language,"Собрать Умру за меня","Build my Umrah","Umramni men uchun tuzing","Умрамни мен учун тузинг"),chrome);Column(Modifier.fillMaxSize().verticalScroll(rememberScrollState()).padding(horizontal=18.dp,vertical=10.dp),verticalArrangement=Arrangement.spacedBy(18.dp)){
        CareIntro(language,carePhone.ifBlank{settings.whatsapp}){number->if(number.isNotBlank())context.startActivity(Intent(Intent.ACTION_DIAL,Uri.parse("tel:${number.filter{it.isDigit()||it=='+'}}")))}
        FormCard(tr(language,"Когда Вы планируете Умру","When do you plan to travel?","Umrani qachon rejalashtirgansiz","Умрани қачон режалаштиргансиз"),CupertinoSymbol.CalendarClock){Segment(listOf(tr(language,"Гибкие даты","Flexible","Moslashuvchan","Мослашувчан") to "flexible_month",tr(language,"Точные даты","Exact dates","Aniq sanalar","Аниқ саналар") to "exact_dates"),timing){timing=it};if(timing=="flexible_month"){ValueRow(tr(language,"Предпочтительный месяц","Preferred month","Afzal oy","Афзал ой"),month.toString());Text(tr(language,"Гибкость","Flexibility","Moslashuvchanlik","Мослашувчанлик"),fontSize=12.sp,fontWeight=FontWeight.SemiBold,color=MaterialTheme.colorScheme.onSurface.copy(alpha=.5f));Segment(listOf("± 3" to 3,"± 7" to 7,"± 14" to 14),flex){flex=it}}else{ValueRow(tr(language,"Начало поездки","Trip starts","Safar boshlanishi","Сафар бошланиши"),start.toString());ValueRow(tr(language,"Возвращение","Return","Qaytish","Қайтиш"),end.toString())}}
        FormCard(tr(language,"Кто едет","Travelers","Kim boradi","Ким боради"),CupertinoSymbol.Persons){StepperRow(tr(language,"Взрослые","Adults","Kattalar","Катталар"),adults,1,20){adults=it};HorizontalDivider();StepperRow(tr(language,"Дети","Children","Bolalar","Болалар"),children,0,20){children=it};HorizontalDivider();StepperRow(tr(language,"Младенцы","Infants","Chaqaloqlar","Чақалоқлар"),infants,0,10){infants=it};HorizontalDivider();StepperRow(tr(language,"Комнаты","Rooms","Xonalar","Хоналар"),rooms,1,10){rooms=it}}
        FormCard(tr(language,"Маршрут","Route","Yo‘nalish","Йўналиш"),CupertinoSymbol.AirplaneTakeoff){ConfiguratorAirportSelector(language,airports,airport,origin){airport=it;origin=it.iata};Text(tr(language,"Маршрут в Саудии","Saudi route","Saudiya yo‘nalishi","Саудия йўналиши"),fontSize=12.sp,fontWeight=FontWeight.SemiBold,color=MaterialTheme.colorScheme.onSurface.copy(alpha=.5f));Segment(listOf(tr(language,"Только Мекка","Makkah","Faqat Makka","Фақат Макка") to "makkah",tr(language,"Мекка + Медина","Makkah + Madinah","Makka + Madina","Макка + Мадина") to "makkah_madinah"),scope){scope=it};if(scope=="makkah_madinah"){Text(tr(language,"Первый город","First city","Birinchi shahar","Биринчи шаҳар"),fontSize=12.sp,fontWeight=FontWeight.SemiBold,color=MaterialTheme.colorScheme.onSurface.copy(alpha=.5f));Segment(listOf("Jeddah" to "jeddah","Madinah" to "madinah"),firstCity){firstCity=it}}}
        FormCard(tr(language,"Что для Вас важнее","What matters most","Siz uchun nima muhim","Сиз учун нима муҳим"),CupertinoSymbol.Star){PriorityGrid(language,priority){priority=it}}
        FormCard(tr(language,"Уровень комфорта","Comfort","Qulaylik darajasi","Қулайлик даражаси"),CupertinoSymbol.Building){Text(tr(language,"Класс отеля","Hotel class","Mehmonxona klassi","Меҳмонхона класси"),fontSize=12.sp,color=MaterialTheme.colorScheme.onSurface.copy(alpha=.5f));Segment(listOf("3★" to 3,"4★" to 4,"5★" to 5),hotelClass){hotelClass=it};Text(tr(language,"Трансфер","Transfer","Transfer","Трансфер"),fontSize=12.sp,color=MaterialTheme.colorScheme.onSurface.copy(alpha=.5f));Segment(listOf(tr(language,"Комфорт","Comfort","Komfort","Комфорт") to "comfortable","SUV" to "private_suv","VIP" to "vip"),transfer){transfer=it};ToggleRow(tr(language,"Только прямые рейсы","Direct flights preferred","To‘g‘ridan parvoz","Тўғридан парвоз"),direct){direct=it};ToggleRow(tr(language,"Багаж включён","Checked baggage","Bagaj","Багаж"),baggage){baggage=it};TextFieldIos(budget,{budget=it},tr(language,"Бюджет, USD","Budget, USD","Budjet, USD","Бюджет, USD"))}
        FormCard(tr(language,"Дополнительные сервисы","Services","Qo‘shimcha xizmatlar","Қўшимча хизматлар"),CupertinoSymbol.Grid){ToggleRow("Ziyarats",ziyarat){ziyarat=it};ToggleRow("eSIM",esim){esim=it};Text(tr(language,"Сопровождение","Guidance","Yo‘l-yo‘riq","Йўл-йўриқ"),fontSize=12.sp,color=MaterialTheme.colorScheme.onSurface.copy(alpha=.5f));Segment(listOf(tr(language,"Нет","None","Yo‘q","Йўқ") to "none",tr(language,"Голос","Voice","Ovoz","Овоз") to "voice",tr(language,"Живой гид","Live guide","Jonli gid","Жонли гид") to "live"),guide){guide=it}}
        FormCard(tr(language,"Контакты","Contact","Aloqa","Алоқа"),CupertinoSymbol.PersonCircle){TextFieldIos(firstName,{firstName=it},tr(language,"Имя","First name","Ism","Исм"));TextFieldIos(lastName,{lastName=it},tr(language,"Фамилия","Last name","Familiya","Фамилия"));TextFieldIos(phone,{phone=it},tr(language,"Телефон","Phone","Telefon","Телефон"));TextFieldIos(telegram,{telegram=it},"Telegram")}
        FormCard(tr(language,"Пожелания","Wishes","Istaklar","Истаклар"),CupertinoSymbol.Message){BasicTextField(notes,{notes=it},Modifier.fillMaxWidth().height(112.dp).background(MaterialTheme.colorScheme.surfaceVariant,RoundedCornerShape(16.dp)).padding(14.dp),textStyle=TextStyle(color=MaterialTheme.colorScheme.onSurface,fontSize=16.sp),decorationBox={inner->Box{if(notes.isBlank())Text(tr(language,"Например: ближе к Хараму, тихий отель, вечерний вылет…","For example: near Haram, quiet hotel, evening flight…","Masalan: Haramga yaqin, sokin mehmonxona…","Масалан: Ҳарамга яқин, сокин меҳмонхона…"),color=MaterialTheme.colorScheme.onSurface.copy(alpha=.35f));inner()}})}
        error?.let{Text(it,color=Color(0xFFFF3B30),fontSize=13.sp)}
        response?.let{SuccessCard(language,it)} ?: IumrahPressable(onClick={val valid=firstName.isNotBlank()&&phone.isNotBlank()&&origin.length==3;if(valid&&!submitting){scopeC.launch{submitting=true;error=null;val req=IumrahCarePackageRequest(language.code,firstName.trim(),lastName.trim(),phone.trim(),telegram.trim(),profile?.iumrahID,origin.uppercase(),timing,if(timing=="flexible_month")month.toString() else null,if(timing=="flexible_month")flex else null,if(timing=="exact_dates")start.toString() else null,if(timing=="exact_dates")end.toString() else null,adults,children,infants,rooms,scope,if(scope=="makkah_madinah")firstCity else null,priority,hotelClass,transfer,direct,baggage,ziyarat,esim,guide,budget.filter(Char::isDigit).toIntOrNull(),notes.trim());runCatching{service.submit(req,accountStore.bearerToken)}.onSuccess{response=it}.onFailure{error=tr(language,"Не удалось отправить запрос в Iumrah Care. Проверьте интернет и попробуйте ещё раз.","We couldn’t send the request to Iumrah Care. Check your connection and try again.","So‘rovni Iumrah Care’ga yuborib bo‘lmadi.","Сўровни Iumrah Care’га юбориб бўлмади.")};submitting=false}}},modifier=Modifier.fillMaxWidth().height(56.dp),enabled=!submitting&&firstName.isNotBlank()&&phone.isNotBlank(),cornerRadius=19.dp,background=Color.Black){Row(Modifier.fillMaxSize().padding(horizontal=19.dp),verticalAlignment=Alignment.CenterVertically){Text(if(submitting)tr(language,"Отправляем…","Sending…","Yuborilmoqda…","Юборилмоқда…") else tr(language,"Отправить запрос","Send request","So‘rov yuborish","Сўров юбориш"),color=Color.White,fontWeight=FontWeight.Bold);Spacer(Modifier.weight(1f));CupertinoIcon(CupertinoSymbol.ArrowRight,null,Modifier.size(18.dp),tint=Color.White)}}
        Text("Iumrah Care",fontSize=12.sp,fontWeight=FontWeight.SemiBold,color=MaterialTheme.colorScheme.onSurface.copy(alpha=.5f));Spacer(Modifier.height(30.dp))
    }}
}

@Composable private fun CareIntro(language:AppLanguage,phone:String,onCall:(String)->Unit){Column(Modifier.fillMaxWidth().background(MaterialTheme.colorScheme.surface,RoundedCornerShape(28.dp)).border(.8.dp,MaterialTheme.colorScheme.onSurface.copy(alpha=.055f),RoundedCornerShape(28.dp)).padding(18.dp),verticalArrangement=Arrangement.spacedBy(14.dp)){Row{Box(Modifier.size(46.dp).background(Color(0xFFFF375F).copy(alpha=.11f),RoundedCornerShape(15.dp)),contentAlignment=Alignment.Center){CupertinoIcon(CupertinoSymbol.HeartFill,null,Modifier.size(19.dp),tint=Color(0xFFFF375F))};Spacer(Modifier.weight(1f));Text("Iumrah Care",fontSize=12.sp,fontWeight=FontWeight.Bold,color=MaterialTheme.colorScheme.onSurface.copy(alpha=.5f),modifier=Modifier.background(MaterialTheme.colorScheme.surfaceVariant,CircleShape).padding(horizontal=11.dp,vertical=7.dp))};Text(tr(language,"Расскажите, какой должна быть Ваша Умра — или позвоните","Tell us what your Umrah should be like — or call us","Umrangiz qanday bo‘lishini ayting — yoki qo‘ng‘iroq qiling","Умрангиз қандай бўлишини айтинг — ёки қўнғироқ қилинг"),fontSize=31.sp,fontWeight=FontWeight.Bold,letterSpacing=(-.7).sp,lineHeight=34.sp);Text(tr(language,"Вы задаёте даты, бюджет и приоритеты. Iumrah Care получает запрос как новую заявку и подбирает персональный вариант.","Set your dates, budget and priorities. Iumrah Care receives a new request and prepares a personal option for you.","Sana, budjet va ustuvorliklarni belgilang. Iumrah Care shaxsiy variant tayyorlaydi.","Сана, бюджет ва устуворликларни белгиланг. Iumrah Care шахсий вариант тайёрлайди."),fontSize=14.sp,color=MaterialTheme.colorScheme.onSurface.copy(alpha=.55f));IumrahPressable({onCall(phone)},Modifier.fillMaxWidth().height(56.dp),enabled=phone.isNotBlank(),cornerRadius=18.dp,background=Color.Black){Row(Modifier.fillMaxSize().padding(horizontal=18.dp),verticalAlignment=Alignment.CenterVertically){CupertinoIcon(CupertinoSymbol.Phone,null,Modifier.size(18.dp),tint=Color.White);Spacer(Modifier.width(10.dp));Text(tr(language,"Позвонить","Call Iumrah Care","Qo‘ng‘iroq qilish","Қўнғироқ қилиш"),color=Color.White,fontSize=17.sp,fontWeight=FontWeight.Bold);Spacer(Modifier.weight(1f));CupertinoIcon(CupertinoSymbol.ArrowUpRight,null,Modifier.size(14.dp),tint=Color.White)}}}}
@Composable private fun FormCard(title:String,icon:CupertinoSymbol,content:@Composable ColumnScope.()->Unit){Column(Modifier.fillMaxWidth().background(MaterialTheme.colorScheme.surface,RoundedCornerShape(28.dp)).border(.8.dp,MaterialTheme.colorScheme.onSurface.copy(alpha=.055f),RoundedCornerShape(28.dp)).padding(18.dp),verticalArrangement=Arrangement.spacedBy(16.dp)){Row(verticalAlignment=Alignment.CenterVertically){Box(Modifier.size(38.dp).background(MaterialTheme.colorScheme.surfaceVariant,RoundedCornerShape(13.dp)),contentAlignment=Alignment.Center){CupertinoIcon(icon,null,Modifier.size(16.dp))};Spacer(Modifier.width(11.dp));Text(title,fontSize=17.sp,fontWeight=FontWeight.Bold)};content()}}
@Composable private fun <T> Segment(items:List<Pair<String,T>>,selected:T,onSelect:(T)->Unit){Row(Modifier.fillMaxWidth().height(36.dp).background(MaterialTheme.colorScheme.surfaceVariant,RoundedCornerShape(11.dp)).padding(2.dp),horizontalArrangement=Arrangement.spacedBy(2.dp)){items.forEach{(label,value)->val active=value==selected;Box(Modifier.weight(1f).fillMaxHeight().background(if(active)MaterialTheme.colorScheme.surface else Color.Transparent,RoundedCornerShape(9.dp)).clickable{onSelect(value)},contentAlignment=Alignment.Center){Text(label,fontSize=12.sp,fontWeight=if(active)FontWeight.Bold else FontWeight.Medium,maxLines=1)}}}}
@Composable private fun StepperRow(title:String,value:Int,min:Int,max:Int,set:(Int)->Unit){Row(Modifier.fillMaxWidth(),verticalAlignment=Alignment.CenterVertically){Text(title,fontWeight=FontWeight.Medium,modifier=Modifier.weight(1f));RoundControl("−"){set((value-1).coerceAtLeast(min))};Text(value.toString(),fontSize=17.sp,fontWeight=FontWeight.Bold,modifier=Modifier.width(38.dp),textAlign=androidx.compose.ui.text.style.TextAlign.Center);RoundControl("+"){set((value+1).coerceAtMost(max))}}}
@Composable private fun RoundControl(text:String,onClick:()->Unit){Box(Modifier.size(34.dp).background(MaterialTheme.colorScheme.surfaceVariant,CircleShape).clickable{onClick()},contentAlignment=Alignment.Center){Text(text,fontSize=20.sp,fontWeight=FontWeight.SemiBold)}}
@Composable private fun ValueRow(label:String,value:String){Row(Modifier.fillMaxWidth().height(50.dp).background(MaterialTheme.colorScheme.surfaceVariant,RoundedCornerShape(16.dp)).padding(horizontal=14.dp),verticalAlignment=Alignment.CenterVertically){Text(label,fontSize=13.sp,color=MaterialTheme.colorScheme.onSurface.copy(alpha=.55f),modifier=Modifier.weight(1f));Text(value,fontWeight=FontWeight.SemiBold)}}
@Composable private fun PriorityGrid(language:AppLanguage,selected:String,onSelect:(String)->Unit){val data=listOf(Triple("lowest_price",tr(language,"Минимальная цена","Lowest price","Eng arzon","Энг арзон"),CupertinoSymbol.CreditCard),Triple("near_haram",tr(language,"Ближе к Хараму","Near Haram","Haramga yaqin","Ҳарамга яқин"),CupertinoSymbol.Location),Triple("balanced",tr(language,"Баланс","Balanced","Balans","Баланс"),CupertinoSymbol.Sliders),Triple("premium",tr(language,"Премиум","Premium","Premium","Премиум"),CupertinoSymbol.Sparkles));Column(verticalArrangement=Arrangement.spacedBy(10.dp)){data.chunked(2).forEach{row->Row(horizontalArrangement=Arrangement.spacedBy(10.dp)){row.forEach{(id,title,icon)->val active=id==selected;Column(Modifier.weight(1f).height(118.dp).background(if(active)Color.Black else MaterialTheme.colorScheme.surfaceVariant,RoundedCornerShape(18.dp)).clickable{onSelect(id)}.padding(14.dp)){CupertinoIcon(icon,null,Modifier.size(18.dp),tint=if(active)Color.White else MaterialTheme.colorScheme.onSurface);Spacer(Modifier.height(10.dp));Text(title,color=if(active)Color.White else MaterialTheme.colorScheme.onSurface,fontSize=14.sp,fontWeight=FontWeight.Bold)}}}}}}
@Composable private fun ToggleRow(title:String,checked:Boolean,onChange:(Boolean)->Unit){Row(Modifier.fillMaxWidth(),verticalAlignment=Alignment.CenterVertically){Text(title,modifier=Modifier.weight(1f),fontWeight=FontWeight.Medium);Switch(checked,onChange)}}
@Composable private fun TextFieldIos(value:String,onChange:(String)->Unit,placeholder:String){BasicTextField(value,onChange,Modifier.fillMaxWidth().height(56.dp).background(MaterialTheme.colorScheme.surfaceVariant,RoundedCornerShape(17.dp)).padding(horizontal=14.dp),singleLine=true,textStyle=TextStyle(color=MaterialTheme.colorScheme.onSurface,fontSize=16.sp),decorationBox={inner->Box(Modifier.fillMaxSize(),contentAlignment=Alignment.CenterStart){if(value.isBlank())Text(placeholder,color=MaterialTheme.colorScheme.onSurface.copy(alpha=.36f));inner()}})}
@Composable private fun SuccessCard(language:AppLanguage,r:IumrahCarePackageRequestResponse){Column(Modifier.fillMaxWidth().background(MaterialTheme.colorScheme.surface,RoundedCornerShape(28.dp)).padding(18.dp),verticalArrangement=Arrangement.spacedBy(14.dp)){Row{Box(Modifier.size(44.dp).background(Color(0xFF34C759).copy(alpha=.12f),CircleShape),contentAlignment=Alignment.Center){CupertinoIcon(CupertinoSymbol.Checkmark,null,Modifier.size(18.dp),tint=Color(0xFF34C759))};Spacer(Modifier.weight(1f));Text(tr(language,"Новая заявка","New request","Yangi so‘rov","Янги сўров"),fontSize=12.sp,fontWeight=FontWeight.Bold,modifier=Modifier.background(MaterialTheme.colorScheme.surfaceVariant,CircleShape).padding(horizontal=11.dp,vertical=7.dp))};Text(tr(language,"Запрос передан Iumrah Care","Request sent to Iumrah Care","So‘rov Iumrah Care’ga yuborildi","Сўров Iumrah Care’га юборилди"),fontSize=27.sp,fontWeight=FontWeight.Bold);Text(tr(language,"Команда увидит параметры поездки и подготовит персональный вариант.","The team will review your trip details and prepare a personal option.","Jamoa safar parametrlarini ko‘rib, shaxsiy variant tayyorlaydi.","Жамоа сафар параметрларини кўриб, шахсий вариант тайёрлайди."),fontSize=14.sp,color=MaterialTheme.colorScheme.onSurface.copy(alpha=.55f));HorizontalDivider();Text("${tr(language,"Номер запроса","Request number","So‘rov raqami","Сўров рақами")}: ${r.requestID}",fontWeight=FontWeight.SemiBold)}}
